---

- name: Install epel release
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Edit firawalld rules
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
    - https
  notify: restart firewalld

- name: Setsebool
  command: setsebool -P httpd_can_network_connect 1

- name: Create proxy_params file
  file:
    path: /etc/nginx/proxy_params
    state: touch

- name: Start nginx service
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
    enabled: yes