---

- name: Install epel release
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Install semanage
  yum:
    name: policycoreutils-python
    state: present

- name: Allow Nginx to listen on tcp port {{ http_port }}
  seport:
    ports: "{{ http_port }}"
    proto: tcp
    setype: http_port_t
    state: present

- name: Edit firawalld rules
  firewalld:
    # service: "{{ item }}"
    port: "{{ http_port }}/tcp"
    permanent: true
    state: enabled
  with_items:
    - http
    - https
  notify: restart firewalld

- name: Setsebool
  command: setsebool -P httpd_can_network_connect 1

- name: Copy nginx.conf
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Create proxy_params file
  file:
    path: /etc/nginx/proxy_params
    state: touch

- name: Start nginx service
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
    enabled: yes