---

- name: Install epel release
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Edit firawalld rules
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
    - https
  notify: restart firewalld

- name: Start nginx service
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
    enabled: yes